platform :ios, '9.0'

target 'DarkSkyWeather' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DarkSkyWeather

    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'SVProgressHUD'
    
end
